CREATE DATABASE IF NOT EXISTS FROTA;
USE FROTA;
CREATE TABLE IF NOT EXISTS  VEICULOS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(30) NOT NULL,
    FABRICANTE VARCHAR(40) NOT NULL,
    PLACA VARCHAR(40) NOT NULL UNIQUE,
    CHASSI VARCHAR(40) NOT NULL UNIQUE,
    DATA_CADASTRO DATETIME NOT NULL,
    STATUS VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS  MOTORISTAS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL,
    CPF VARCHAR(15) UNIQUE NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    DATA_CADASTRO DATETIME NOT NULL
);
CREATE TABLE IF NOT EXISTS  GESTAO_VEICULO_MOTORISTAS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	ID_VEICULO INT NOT NULL,
	ID_MOTORISTA INT NOT NULL,
	DATA_INICIO DATETIME NOT NULL,
	DATA_FIM DATETIME,
	STATUS CHAR(30) NOT NULL,
    CONSTRAINT FK_MOTORISTA FOREIGN KEY (ID_MOTORISTA) REFERENCES MOTORISTAS(ID),
    CONSTRAINT FK_VEICULOS FOREIGN KEY (ID_VEICULO) REFERENCES VEICULOS(ID)
);

DELIMITER $
CREATE DEFINER=`root`@`localhost` PROCEDURE `FIM_JORNADA`(ID int)
BEGIN
SET @ID_MOT:= 0;
SET @ID_VEIC := 0;

SELECT @ID_MOT := ID_MOTORISTA FROM GESTAO_VEICULO_MOTORISTAS WHERE ID = ID;
SELECT @ID_VEIC := ID_VEICULO FROM GESTAO_VEICULO_MOTORISTAS WHERE ID = ID;

UPDATE GESTAO_VEICULO_MOTORISTAS SET STATUS = 'ENCERRADA',DATA_FIM=NOW() WHERE ID = ID;
UPDATE MOTORISTAS SET STATUS = 'LIVRE' WHERE ID = @ID_MOT;
UPDATE VEICULOS SET STATUS = 'LIVRE' WHERE ID = @ID_VEIC;
 
END